const db = require('../config/db');

class ReadingRepository {
  async getReadings(clientId, options = {}) {
    let sql = `SELECT * FROM readings WHERE client_id = ?`;
    const params = [clientId];
    if (options.tankId) {
      sql += ` AND tank_id = ?`;
      params.push(options.tankId);
    }
    sql += ` ORDER BY captured_at DESC`;
    if (options.limit) {
      sql += ` LIMIT ?`;
      params.push(parseInt(options.limit, 10));
    }
    const [rows] = await db.query(sql, params);
    return rows;
  }

  async getLastReadingForTank(clientId, tankId) {
    const [rows] = await db.query(
      `SELECT * FROM readings WHERE client_id = ? AND tank_id = ? ORDER BY captured_at DESC LIMIT 1`,
      [clientId, tankId]
    );
    return rows[0] || null;
  }

  async getPreviousCapture(clientId, tankId, parameterId) {
    const [rows] = await db.query(
      `SELECT * FROM previous_captures WHERE client_id = ? AND tank_id = ? AND parameter_id = ? ORDER BY captured_at DESC LIMIT 1`,
      [clientId, tankId, parameterId]
    );
    return rows[0] || null;
  }

  async saveReadingTransaction(readingData) {
    const connection = await db.getConnection();
    try {
      await connection.beginTransaction();

      const {
        id,
        client_id,
        tank_id,
        captured_by,
        captured_by_name,
        captured_at,
        final_level,
        source,
        image_url,
        inspection_values,
        alertsToCreate,
        violationsToCreate
      } = readingData;

      // 1. Insert reading record
      await connection.query(
        `INSERT INTO readings (id, client_id, tank_id, captured_by, captured_by_name, captured_at, final_level, source, image_url, inspection_values_json)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          id,
          client_id,
          tank_id,
          captured_by || null,
          captured_by_name || null,
          captured_at ? new Date(captured_at) : new Date(),
          final_level != null ? parseFloat(final_level) : null,
          source || 'app',
          image_url || null,
          JSON.stringify(inspection_values || {})
        ]
      );

      // 2. Insert normalized reading_values and update previous_captures
      const captureTime = captured_at ? new Date(captured_at) : new Date();
      if (inspection_values && typeof inspection_values === 'object') {
        for (const [pId, val] of Object.entries(inspection_values)) {
          let numVal = null;
          let txtVal = null;
          if (typeof val === 'number') numVal = val;
          else if (typeof val === 'string') {
            txtVal = val;
            const parsed = parseFloat(val);
            if (!isNaN(parsed)) numVal = parsed;
          } else if (val && typeof val === 'object') {
            txtVal = JSON.stringify(val);
          }

          await connection.query(
            `INSERT INTO reading_values (client_id, reading_id, tank_id, parameter_id, captured_at, text_value, numeric_value, raw_value_json)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
            [client_id, id, tank_id, pId, captureTime, txtVal, numVal, JSON.stringify(val)]
          );

          await connection.query(
            `INSERT INTO previous_captures (client_id, tank_id, parameter_id, reading_id, captured_at, value_json)
             VALUES (?, ?, ?, ?, ?, ?)`,
            [client_id, tank_id, pId, id, captureTime, JSON.stringify(val)]
          );
        }
      }

      // 3. Process Alerts generated by constraints
      if (alertsToCreate && Array.isArray(alertsToCreate)) {
        for (const a of alertsToCreate) {
          await connection.query(
            `INSERT INTO alerts (id, client_id, tank_id, tank_code, tank_name, reading_id, constraint_id, param_id, message, severity, status, live, timestamp, capture_image_url)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', 1, ?, ?)`,
            [
              a.id,
              client_id,
              tank_id,
              a.tank_code || null,
              a.tank_name || null,
              id,
              a.constraint_id || null,
              a.param_id || null,
              a.message || 'Constraint Alert',
              a.severity || 'warning',
              captureTime,
              a.image_url || null
            ]
          );
        }
      }

      // 4. Process Violations
      if (violationsToCreate && Array.isArray(violationsToCreate)) {
        for (const v of violationsToCreate) {
          await connection.query(
            `INSERT INTO violations (id, client_id, tank_id, tank_code, tank_name, reading_id, constraint_id, param_id, message, severity, status, live, timestamp)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', 1, ?)`,
            [
              v.id,
              client_id,
              tank_id,
              v.tank_code || null,
              v.tank_name || null,
              id,
              v.constraint_id || null,
              v.param_id || null,
              v.message || 'Constraint Violation',
              v.severity || 'high',
              captureTime
            ]
          );
        }
      }

      // 5. Update dashboard stats
      await connection.query(
        `INSERT INTO dashboard_stats (client_id, tank_id, count_value, last_captured_at, last_captured_by, last_reading_json, updated_at)
         VALUES (?, ?, 1, ?, ?, ?, NOW())
         ON DUPLICATE KEY UPDATE count_value = count_value + 1, last_captured_at = VALUES(last_captured_at), last_captured_by = VALUES(last_captured_by), last_reading_json = VALUES(last_reading_json), updated_at = NOW()`,
        [client_id, tank_id, captureTime, captured_by || null, JSON.stringify(inspection_values || {})]
      );

      await connection.commit();
      return { success: true, readingId: id };
    } catch (err) {
      await connection.rollback();
      throw err;
    } finally {
      connection.release();
    }
  }
}

module.exports = new ReadingRepository();
